discovery:
  build: ../discovery
  ports:
   - "8761:8761"
configserver:
  build: ../config
  ports:
   - "8888:8888"
  links:
   - discovery
  environment:
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/"  
gateway:
  build: ../api-gateway
  ports:
   - "8080:8080"
  links:
   - discovery
   - configserver
   - catalog
  environment:
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/" 
catalog:
  build: ../catalog
  links:
   - discovery
   - configserver
  environment:
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/" 
pricing:
  build: ../pricing
  links:
   - discovery
   - configserver
  environment:
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/" 
commerceui:
  build: ../ecommerce-ui
  ports:
     - "4200:4200"